spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "*"
            allowed-methods:
              - "*"
            allowed-headers:
              - "*"
            allow-credentials: true
      routes:
        - id: bing-route
          uri: https://cn.bing.com
          predicates:
            - name: Path
              args:
                pattern: /search
                matchTrailingSlash: true  # 匹配路径末尾的斜杠
            - name: Query #这个是Predicate的内置参数
              args:
                param: q
                regexp: haha
#            - Vip=user,xiaohuo
            - name: Vip #这个是自定义参数
              args:
                param: user
                value: xiaohuo
          order: 10
        - id: order_route
          uri: lb://service-order
          predicates:
            - name: Path
              args:
                pattern: /api/order/**
                matchTrailingSlash: true  # 匹配路径末尾的斜杠
          filters:
            - RewritePath=/api/order/(?<segment>.*), /$\{segment}
            - OnceToken=X-Response-Token, jwt #添加响应头
          order: 1
        - id: product_route
          uri: lb://service-product
          predicates:
            - name: Path
              args:
                pattern: /api/product/**
                matchTrailingSlash: true  # 匹配路径末尾的斜杠
          filters:
            - RewritePath=/api/product/(?<segment>.*), /$\{segment}
          order: 2
      default-filters: #默认过滤器
        - AddResponseHeader=X-Response-abc, 123 #添加响应头