#阿里云oss配置
aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tNt81zZ6kJDKihR3Vx4
    accessKeySecret: gZFyTStXdVdOnoemhNixysl8MT2vel4
    bucketName: web-tlias-xiaohuo
